2022-10-01 13:02:41,520 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:02:51,812 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:02:53,971 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:02:54,378 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:02:58,868 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 15:50:22,043 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 15:55:31,680 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 17:04:35,482 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 17:04:41,434 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 17:04:54,701 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-10-03 17:12:20,747 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:80]
2022-10-03 17:12:32,906 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:80]
2022-10-03 17:12:59,493 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:80]
2022-10-03 17:25:34,141 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:80]
